var EARTH_TIMELAPSE_CONFIG = {
  "version" : 5,
  "landsatVersion" : "2015",
  "browserScaleFactor" : 1,
  "isHyperwall" : false,
  "useGoogleMaps" : false,
  "useGoogleSearch" : false,
  "defaultPlaybackSpeed" : 0.5,
  "enableAutoMode" : false,
  "screenTimeoutInMilliseconds" : 4 * 60 * 1000,
  "waypointDelayInMilliseconds" : 1 * 20 * 1000,
  "showEVA" : false,
  "showForestAlerts" : false,
  "showLodes" : true,
  "showGlobalWindPower": true,
  "enableLetterboxMode" : false,   // Turn this to True for letter mode
  "useFaderShader" : true,
  "enableWaypointText" : true,
  "enableRecordingMode" : false,
  "launchMode" : "maximized",
  "clearProfile" : true,
  "rootTilePath" : "http://tiles.cmucreatelab.org/earthtimelapse/data/",
  // "waypointSliderContentPath" : "https://docs.google.com/spreadsheets/d/1hFpDXOyjvjTpad7HpB0K-3thuYqSOlDJ4oExCTcscUk/edit#gid=0",
  // "waypointSliderContentPath":"https://docs.google.com/spreadsheets/d/1JLY9J4XYsWaz-lD8tzAIF1oBjaxIQbqe0AISt5Q48ro/edit#gid=1186806884", //very faster loading purpose
  "waypointSliderContentPath":"https://docs.google.com/spreadsheets/d/1JLY9J4XYsWaz-lD8tzAIF1oBjaxIQbqe0AISt5Q48ro/edit#gid=1769400286", // bit faster loading purpose
  "showMonthlyRefugees": true,
  "showAnnualRefugees": true,
  "showVsi": true,
  "showHealthImpact": true,
  "showZika": true,
  "showDengue": true,
  "showChiku": true,
  "subsampleAnnualRefugees": true,
  "showShareButton": true,
  "showSeaLevelRise": true,
  "showHiv": true,
  "showObesity": true,
  "showVaccineConfidence": true,
  "showNdviAnomaly": true,
  "showEbola": true,
  "showUrbanFragility": true,
  "showGtd": true,
  "showWaterOccurrence": true,
  "showWaterChange": true
};
