var ISO_TO_SUBREGION = {
    'abw': 'Caribbean', 'aia': 'Caribbean', 'atg': 'Caribbean', 
    'bhs': 'Caribbean', 'blm': 'Caribbean', 'brb': 'Caribbean',
    'cub': 'Caribbean', 'cuw': 'Caribbean', 'cym': 'Caribbean',
    'dma': 'Caribbean', 'dom': 'Caribbean', 'grd': 'Caribbean',
    'hti': 'Caribbean', 'jam': 'Caribbean', 'kna': 'Caribbean',
    'lca': 'Caribbean', 'maf': 'Caribbean', 'msr': 'Caribbean',
    'pri': 'Caribbean', 'sxm': 'Caribbean', 'tca': 'Caribbean',
    'tto': 'Caribbean', 'vct': 'Caribbean', 'vgb': 'Caribbean',
    'vir': 'Caribbean',
    'ago': 'Middle Africa', 'caf': 'Middle Africa', 'cmr': 'Middle Africa',
    'cod': 'Middle Africa', 'cog': 'Middle Africa', 'gab': 'Middle Africa',
    'gnq': 'Middle Africa', 'stp': 'Middle Africa', 'tcd': 'Middle Africa',
    'alb': 'Southern Europe', 'and': 'Southern Europe', 
    'bih': 'Southern Europe', 'esp': 'Southern Europe',
    'grc': 'Southern Europe', 'hrv': 'Southern Europe',
    'ita': 'Southern Europe', 'mkd': 'Southern Europe',
    'mlt': 'Southern Europe', 'mne': 'Southern Europe',
    'prt': 'Southern Europe', 'smr': 'Southern Europe',
    'srb': 'Southern Europe', 'svn': 'Southern Europe',
    'vat': 'Southern Europe', 
    'fsm': 'Micronesia', 'gum': 'Micronesia', 'kir': 'Micronesia',
    'mhl': 'Micronesia', 'mnp': 'Micronesia', 'nru': 'Micronesia',
    'plw': 'Micronesia', 
    'ben': 'Western Africa', 'bfa': 'Western Africa', 'civ': 'Western Africa',
    'cpv': 'Western Africa', 'gha': 'Western Africa', 'gin': 'Western Africa',
    'gmb': 'Western Africa', 'gnb': 'Western Africa', 'lbr': 'Western Africa',
    'mli': 'Western Africa', 'mrt': 'Western Africa', 'ner': 'Western Africa',
    'nga': 'Western Africa', 'sen': 'Western Africa', 'shn': 'Western Africa',
    'sle': 'Western Africa', 'tgo': 'Western Africa',
    'kaz': 'Central Asia', 'kgz': 'Central Asia', 'tjk': 'Central Asia',
    'tkm': 'Central Asia', 'uzb': 'Central Asia', 
    'brn': 'South-Eastern Asia', 'idn': 'South-Eastern Asia',
    'khm': 'South-Eastern Asia', 'lao': 'South-Eastern Asia',
    'mmr': 'South-Eastern Asia', 'mys': 'South-Eastern Asia',
    'phl': 'South-Eastern Asia', 'sgp': 'South-Eastern Asia',
    'tha': 'South-Eastern Asia', 'tls': 'South-Eastern Asia',
    'vnm': 'South-Eastern Asia',
    'bdi': 'Eastern Africa', 'com': 'Eastern Africa', 'dji': 'Eastern Africa', 
    'eri': 'Eastern Africa', 'eth': 'Eastern Africa', 'ken': 'Eastern Africa',
    'mdg': 'Eastern Africa', 'moz': 'Eastern Africa', 'mus': 'Eastern Africa',
    'mwi': 'Eastern Africa', 'rwa': 'Eastern Africa', 'ssd': 'Eastern Africa',
    'som': 'Eastern Africa', 'syc': 'Eastern Africa', 'tza': 'Eastern Africa',
    'uga': 'Eastern Africa', 'zmb': 'Eastern Africa', 'zwe': 'Eastern Africa',
    'ala': 'Northern Europe', 'dnk': 'Northern Europe', 
    'est': 'Northern Europe', 'fin': 'Northern Europe',
    'fro': 'Northern Europe', 'gbr': 'Northern Europe',
    'ggy': 'Northern Europe', 'imn': 'Northern Europe',
    'irl': 'Northern Europe', 'isl': 'Northern Europe',
    'jey': 'Northern Europe', 'ltu': 'Northern Europe',
    'lva': 'Northern Europe', 'nor': 'Northern Europe',
    'swe': 'Northern Europe',
    'atf': 'Seven seas (open ocean)', 'hmd': 'Seven seas (open ocean)',
    'iot': 'Seven seas (open ocean)', 'sgs': 'Seven seas (open ocean)',
    'arg': 'South America', 'bol': 'South America',
    'bra': 'South America', 'chl': 'South America',
    'col': 'South America', 'ecu': 'South America',
    'flk': 'South America', 'guy': 'South America',
    'per': 'South America', 'pry': 'South America',
    'sur': 'South America', 'ury': 'South America',
    'ven': 'South America',
    'chn': 'Eastern Asia', 'hkg': 'Eastern Asia', 'jpn': 'Eastern Asia',
    'kor': 'Eastern Asia', 'mac': 'Eastern Asia', 'mng': 'Eastern Asia',
    'prk': 'Eastern Asia', 'twn': 'Eastern Asia',
    'bmu': 'Northern America', 'can': 'Northern America',
    'grl': 'Northern America', 'spm': 'Northern America',
    'usa': 'Northern America',
    'asm': 'Polynesia', 'cok': 'Polynesia', 'niu': 'Polynesia',
    'pcn': 'Polynesia', 'pyf': 'Polynesia', 'ton': 'Polynesia',
    'wlf': 'Polynesia', 'wsm': 'Polynesia',
    'bwa': 'Southern Africa', 'lso': 'Southern Africa', 
    'nam': 'Southern Africa', 'swz': 'Southern Africa',
    'zaf': 'Southern Africa', 
    'are': 'Western Asia', 'arm': 'Western Asia', 'aze': 'Western Asia',
    'bhr': 'Western Asia', 'cyp': 'Western Asia', 'geo': 'Western Asia',
    'irq': 'Western Asia', 'isr': 'Western Asia', 'jor': 'Western Asia',
    'kwt': 'Western Asia', 'lbn': 'Western Asia', 'omn': 'Western Asia',
    'pse': 'Western Asia', 'qat': 'Western Asia', 'sau': 'Western Asia',
    'syr': 'Western Asia', 'tur': 'Western Asia', 'yem': 'Western Asia',
    'afg': 'Southern Asia', 'bgd': 'Southern Asia', 'btn': 'Southern Asia',
    'ind': 'Southern Asia', 'irn': 'Southern Asia', 'lka': 'Southern Asia', 
    'mdv': 'Southern Asia', 'npl': 'Southern Asia', 'pak': 'Southern Asia',
    'fji': 'Melanesia', 'ncl': 'Melanesia', 'png': 'Melanesia',
    'slb': 'Melanesia', 'vut': 'Melanesia',
    'aus': 'Australia and New Zealand', 'nfk': 'Australia and New Zealand',
    'nzl': 'Australia and New Zealand',
    'bgr': 'Eastern Europe', 'blr': 'Eastern Europe', 'cze': 'Eastern Europe',
    'hun': 'Eastern Europe', 'mda': 'Eastern Europe', 'pol': 'Eastern Europe',
    'rou': 'Eastern Europe', 'rus': 'Eastern Europe', 'svk': 'Eastern Europe',
    'ukr': 'Eastern Europe',
    'dza': 'Northern Africa', 'egy': 'Northern Africa', 
    'lby': 'Northern Africa', 'mar': 'Northern Africa',
    'esh': 'Northern Africa', 'sdn': 'Northern Africa',
    'tun': 'Northern Africa',
    'blz': 'Central America', 'cri': 'Central America', 
    'gtm': 'Central America', 'hnd': 'Central America',
    'mex': 'Central America', 'nic': 'Central America',
    'pan': 'Central America', 'slv': 'Central America',
    'ata': 'Antarctica',
    'aut': 'Western Europe', 'bel': 'Western Europe', 'che': 'Western Europe',
    'deu': 'Western Europe', 'fra': 'Western Europe', 'lie': 'Western Europe',
    'lux': 'Western Europe', 'mco': 'Western Europe', 'nld': 'Western Europe'
}

