var EARTH_TIMELAPSE_CONFIG = {
  "version": 6,
  "landsatVersion": "2016",
  "landsatUrl": "http://storage.googleapis.com/earthengine-timelapse/herwig/earthtime_annual_1984_2016/v14/1068x600",
  "rootTilePath": "https://tiles.earthtime.org",
  "showStories" : true,
  "waypointSliderContentPath": undefined,
  "csvLayersContentPath": undefined,
  "showCsvLayers": true,
  "dotmapsContentPath": undefined,
  "dotmapsServerHost": undefined,
  "showCustomDotmaps": true,
  "showShareButton": true,
  "showSettingsButton": false,
  "showThumbnailTool" : true,
  "thumbnailServerHost": undefined,
  "headlessClientHost": undefined,
  "showExtrasMenu": false,
  "enableStoryEditor": true,
  "isHyperwall": false,
  "useGoogleMaps": false,
  "useGoogleSearch": false,
  "googleMapsAPIKey": "",
  "browserScaleFactor": 1,
  "defaultPlaybackSpeed": 0.5,
  "enableAutoMode": false,
  "autoModeCriteria" : {
    "cycleThroughStoriesAndThemes": false,
    "cycleThroughStories": false
  },
  "screenTimeoutInMilliseconds": 4 * 60 * 1000,
  "waypointDelayInMilliseconds": 1 * 20 * 1000,
  "enableLetterboxMode": false,
  "enableThemeHamburgerButton": true,
  "useFaderShader": true,
  "enableWaypointText": true,
  "enableRecordingMode": false,
  "launchMode": "maximized",
  "clearProfile": true,
  "showMonthlyRefugees": true,
  "showAnnualRefugees": true,
  "showAnnualReturns": true,
  "subsampleAnnualRefugees": true,
  "subsampleAnnualReturns": true,
  "showHealthImpact": true,
  "showZika": true,
  "showDengue": true,
  "showChiku": true,
  "showSeaLevelRise": true,
  "showTintedSeaLevelRise": false,
  "showUrbanFragility": true,
  "showGtd": true,
  "showHiv": true,
  "showObesity": true,
  "showVaccineConfidence": true,
  "showNdviAnomaly": true,
  "showEbola": true,
  "showWaterOccurrence" : true,
  "showWaterChange" : true,
  "showCumulativeActiveMining": false,
  "showIomIdp": true,
  "showBerkeleyEarthTemperatureAnomaly": true,
  "showUppsalaConflict": true,
  "showOmiNo2": true,
  "showChinaInfrastructure": false,
  "showBePm25": true,
  "showIrena": true,
  "showCityLabelMap": false,
  "showTsip": true,
  "showEcco2": true,
  "showGdpPpp": true,
  "showTintedLandsat": false,
  "showGfsTimemachine": false,
  "showWindVectors": true,
  "showExpandingCities": true,
  "showGoes16": true,
  "showDscovr": true,
  "showAnnualGlobalPm25": true,
  "useRetinaDarkBaseMap": false,
  "useRetinaLightBaseMap": false,
  "useRetinaNoLabelsDarkBaseMap": false,
  "useRetinaNoLabelsLightBaseMap": false,
  "showForestAlerts": false,
  "showLodes": true,
  "showGlobalWindPower": true
};
