var EARTH_TIMELAPSE_CONFIG = {
  "version" : 6,
  "browserScaleFactor" : 1,
  "showShareButton": false,
  "isHyperwall" : false,
  "useGoogleMaps" : false,
  "useGoogleSearch" : false,
  "defaultPlaybackSpeed" : 0.5,
  "enableAutoMode" : false,
  "screenTimeoutInMilliseconds" : 4 * 60 * 1000,
  "waypointDelayInMilliseconds" : 1 * 20 * 1000,
  "showEVA" : false,
  "showForestAlerts" : false,
  "showLODES" : false,
  "showGlobalWindPower": false,
  "enableLetterboxMode" : false,
  "useFaderShader" : true,
  "enableWaypointText" : true,
  "enableRecordingMode" : false,
  "launchMode" : "maximized",
  "clearProfile" : true,
  "rootTilePath" : "http://tiles.cmucreatelab.org/earthtimelapse/data/",
  "waypointSliderContentPath" : "",
  "showMonthlyRefugees": false,
  "showAnnualRefugees": false,
  "subsampleAnnualRefugees": false,
  "showVsi": false,
  "showHealthImpact": false,
  "showZika": false,
  "showDengue": false,
  "showChiku": false,
  "showSeaLevelRise": false,
  "showUrbanFragility": false,
  "showGtd": false,
  "showHiv": false,
  "showObesity": false,
  "showVaccineConfidence": false,
  "showNdviAnomaly": false,
  "showEbola": false
};
